#' Example electrofishing catch records
#'
#' A simulated long-format multi-pass electrofishing dataset for four
#' reaches, each surveyed on two dates, with two species and three
#' removal passes per survey. Counts were generated from a constant-
#' probability removal (binomial depletion) model so that depletion
#' estimators recover sensible abundances. Pairs with [example_reach].
#'
#' @format A data frame with 48 rows and 8 columns:
#' \describe{
#'   \item{reach_id}{Reach identifier (character), e.g. `"R01"`.}
#'   \item{date}{Survey date (Date).}
#'   \item{pass_number}{Removal pass index, 1-3 (integer).}
#'   \item{species}{Species code (character): `"BNT"` or `"RBT"`.}
#'   \item{count}{Number of fish captured on the pass (integer).}
#'   \item{effort_seconds}{Shocking effort for the pass, in seconds (numeric).}
#'   \item{amperage}{Mean shocking current for the pass, in amperes (numeric).}
#'   \item{voltage}{Mean shocking voltage for the pass (numeric).}
#' }
#'
#' @details Generated by `data-raw/make_example_data.R` with `set.seed(42)`.
#' @family example data
#' @seealso [example_reach], [analyze_cpue()]
"example_catch"

#' Example reach metadata
#'
#' Reach-level metadata for the four reaches in [example_catch], keyed by
#' `reach_id`.
#'
#' @format A data frame with 4 rows and 7 columns:
#' \describe{
#'   \item{reach_id}{Reach identifier (character), e.g. `"R01"`.}
#'   \item{length_m}{Reach length in metres (numeric).}
#'   \item{mean_width_m}{Mean wetted width in metres (numeric).}
#'   \item{habitat_class}{Dominant habitat class (character).}
#'   \item{crew}{Survey crew (character).}
#'   \item{gear}{Electrofishing gear (character).}
#'   \item{area_m2}{Surveyed area in square metres, `length_m * mean_width_m`
#'     (numeric).}
#' }
#'
#' @details Generated by `data-raw/make_example_data.R`.
#' @family example data
#' @seealso [example_catch], [analyze_cpue()]
"example_reach"
